// <auto-generated />
using MVCWeather.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCWeather.Migrations
{
    [DbContext(typeof(MVCWeatherContext))]
    partial class MVCWeatherContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("MVCWeather.Models.Weather", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("temp")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Weather");
                });
#pragma warning restore 612, 618
        }
    }
}
